In [4]:
i = [1,2,3,4,5,6]
print(i[-2])

5


In [5]:
from math import sin

In [6]:
sin(5)

-0.9589242746631385

In [7]:
x = {1,2,3}
x.add(3)
x.add(4)
print(x)

{1, 2, 3, 4}


In [1]:
import torch

In [45]:

nb_obs = 4
nb_action = 2


linear1 = torch.nn.Linear(nb_obs,5)
linear2 = torch.nn.Linear(5,4)
linear3 = torch.nn.Linear(4,nb_action)

nn = torch.nn.Sequential(
    linear1,
    torch.nn.ReLU(),
    linear2,
    torch.nn.Tanh(),
    linear3,
    torch.nn.Softmax()
)
print(nn.state_dict())
input = torch.Tensor(20,4)

OrderedDict([('0.weight', tensor([[ 0.0939,  0.4384,  0.3160,  0.3838],
        [-0.1212,  0.2368, -0.2425,  0.2675],
        [ 0.2670, -0.4848, -0.0886, -0.3443],
        [ 0.4202,  0.0071,  0.4319,  0.4826],
        [-0.3548,  0.0416,  0.4812, -0.0338]])), ('0.bias', tensor([ 4.5143e-01, -4.2366e-01,  6.8257e-02,  1.6548e-01, -1.4728e-04])), ('2.weight', tensor([[-0.1726, -0.0908,  0.3564, -0.3988, -0.1078],
        [ 0.0274,  0.2151, -0.3052, -0.0119,  0.1076],
        [ 0.4391, -0.0397,  0.4101, -0.0462, -0.2995],
        [-0.1188,  0.2931, -0.2924,  0.0457,  0.0563]])), ('2.bias', tensor([ 0.1093,  0.1346,  0.1007, -0.2237])), ('4.weight', tensor([[-0.0729,  0.4099, -0.2600,  0.1780],
        [-0.4748,  0.3381,  0.4188, -0.1520]])), ('4.bias', tensor([0.4063, 0.3594]))])


In [48]:
# Calcul de log de la policy



output = torch.log(nn(input))
print(output)
output.sum().backward()




tensor([[-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755],
        [-0.8265, -0.5755]], grad_fn=<LogBackward0>)


In [40]:
output_true = torch.Tensor(20,2)
print(nn(input))
mse = torch.nn.MSELoss()
loss = mse(output_true,nn(input))

tensor([[0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.5235, 0.4765],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357],
        [0.4643, 0.5357]], grad_fn=<SoftmaxBackward0>)


In [41]:
loss.backward()

In [42]:
nn.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.4990,  0.4449,  0.1523, -0.3675],
                      [-0.3149, -0.2334,  0.3947,  0.1759],
                      [ 0.0627,  0.4338, -0.4770,  0.3107],
                      [-0.1130, -0.3490, -0.0528, -0.2363],
                      [ 0.4454,  0.0306,  0.3574, -0.2279]])),
             ('0.bias', tensor([ 0.1863, -0.1371, -0.4190,  0.0356,  0.4500])),
             ('2.weight',
              tensor([[ 0.2942,  0.2125,  0.3233, -0.2051,  0.3066],
                      [ 0.3281,  0.1495,  0.3709,  0.1124,  0.3602],
                      [-0.2613, -0.0206, -0.0374, -0.1571, -0.4169],
                      [ 0.1661, -0.1480,  0.4107,  0.1690,  0.2141]])),
             ('2.bias', tensor([ 0.3514, -0.0698,  0.4260,  0.3785])),
             ('4.weight',
              tensor([[ 0.2572, -0.4389, -0.2848,  0.0792],
                      [ 0.3587,  0.1939,  0.1810, -0.4356]])),
             ('4.bias', tensor([0.3065, 0.4587]))])

In [55]:
torch.matmul(linear1.weight.grad,torch.transpose(linear1.weight.grad,1,0))

tensor([[5.3396e-39, 0.0000e+00, 3.1333e-39, 1.7007e-39, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.1333e-39, 0.0000e+00, 1.8387e-39, 9.9801e-40, 0.0000e+00],
        [1.7007e-39, 0.0000e+00, 9.9801e-40, 5.4171e-40, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [53]:
torch.transpose(linear1.weight.grad,1,0)

tensor([[-4.7045e-36,  0.0000e+00, -2.7607e-36, -1.4985e-36,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 7.3072e-20,  0.0000e+00,  4.2880e-20,  2.3275e-20,  0.0000e+00],
        [-4.2627e-42,  0.0000e+00, -2.5027e-42, -1.3565e-42,  0.0000e+00]])

In [56]:
linear1.weight.grad

tensor([[-4.7045e-36,  0.0000e+00,  7.3072e-20, -4.2627e-42],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-2.7607e-36,  0.0000e+00,  4.2880e-20, -2.5027e-42],
        [-1.4985e-36,  0.0000e+00,  2.3275e-20, -1.3565e-42],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])